-- =================================================================
-- INSERT 28 EMERGENCY VET CLINICS
-- Westchester (16) + Rochester (12)
-- With all differentiation features populated
-- =================================================================

INSERT INTO clinics (
  name, slug, address, city, state, zip_code, phone, website,
  is_24_7, availability_type, latitude, longitude,
  exotic_pets_accepted, has_exotic_specialist,
  services_offered, has_surgery_suite, has_icu, has_specialists,
  payment_methods, accepts_care_credit, accepts_pet_insurance,
  cost_tier, parking_type, wheelchair_accessible,
  verification_status
) VALUES

-- =================================================================
-- WESTCHESTER COUNTY, NY (16 clinics)
-- =================================================================

-- 1. VEG White Plains (24/7, Premium)
(
  'VEG White Plains',
  'veg-white-plains',
  '201 Tarrytown Rd',
  'Westchester',
  'NY',
  '10607',
  '(914) 949-8779',
  'https://www.veg.com/locations/new-york/white-plains',
  true,
  'true-24-7',
  41.0326,
  -73.7629,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'small-mammals', 'exotic-all'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'blood-transfusions', 'oxygen-therapy', 'pain-management'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 2. Katonah-Bedford Veterinary Center (24/7, Premium)
(
  'Katonah-Bedford Veterinary Center',
  'katonah-bedford-vet-center',
  '546 N Bedford Rd',
  'Westchester',
  'NY',
  '10507',
  '(914) 241-7700',
  'https://vcahospitals.com/katonah-bedford',
  true,
  'true-24-7',
  41.2587,
  -73.6876,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'cardiology', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 3. Animal Specialty Center - Yonkers (24/7, Moderate)
(
  'Animal Specialty Center',
  'animal-specialty-center-yonkers',
  '9 Odell Plaza',
  'Westchester',
  'NY',
  '10701',
  '(914) 457-4000',
  'https://www.animalspecialtycenter.com',
  true,
  'true-24-7',
  40.9176,
  -73.8990,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'mri', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'moderate',
  'free-lot',
  true,
  'verified'
),

-- 4. Guardian Veterinary Specialists (24/7, Premium)
(
  'Guardian Veterinary Specialists',
  'guardian-vet-specialists-brewster',
  '3 Hardscrabble Heights',
  'Westchester',
  'NY',
  '10509',
  '(914) 704-3400',
  'https://guardianveterinaryspecialists.com',
  true,
  'true-24-7',
  41.3976,
  -73.6164,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'cardiology', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 5. Animal Healthcare Center - Briarcliff Manor (Extended Hours)
(
  'Animal Healthcare Center at Veterinary Village',
  'animal-healthcare-briarcliff',
  '513 North State Rd',
  'Westchester',
  'NY',
  '10510',
  '(914) 941-4904',
  'https://emergencyvet.org',
  false,
  'extended-hours',
  41.1465,
  -73.8268,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'ultrasound-imaging', 'mri', 'ct-scan'],
  true,
  false,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'moderate',
  'free-lot',
  true,
  'unverified'
),

-- 6. MedVet Norwalk, CT (24/7, Premium)
(
  'MedVet Norwalk',
  'medvet-norwalk',
  '246 East Ave',
  'Westchester',
  'CT',
  '06855',
  '(203) 854-9960',
  'https://www.medvetforpets.com/norwalk',
  true,
  'true-24-7',
  41.1171,
  -73.4104,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'small-mammals'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'cardiology', 'neurology', 'oncology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 7. Cornell University Veterinary Specialists - Stamford (24/7, Luxury)
(
  'Cornell University Veterinary Specialists',
  'cornell-vet-stamford',
  '880 Canal Street',
  'Westchester',
  'CT',
  '06902',
  '(203) 595-2777',
  'https://www.cuvs.org',
  true,
  'true-24-7',
  41.0534,
  -73.5387,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'exotic-all'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'cardiology', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'luxury',
  'free-lot',
  true,
  'verified'
),

-- 8. VCA Veterinary Referral and Emergency Center - Norwalk (24/7, Premium)
(
  'VCA Veterinary Referral and Emergency Center',
  'vca-referral-norwalk',
  '123 W Cedar St',
  'Westchester',
  'CT',
  '06854',
  '(203) 852-2009',
  'https://vcahospitals.com/norwalk-referral',
  true,
  'true-24-7',
  41.0980,
  -73.4266,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'cardiology', 'oncology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 9. VEG Cos Cob, CT (24/7, Premium)
(
  'VEG Cos Cob',
  'veg-cos-cob',
  '409 E Putnam Ave',
  'Westchester',
  'CT',
  '06807',
  '(203) 909-6560',
  'https://www.veg.com/locations/connecticut/cos-cob',
  true,
  'true-24-7',
  41.0331,
  -73.5982,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'small-mammals', 'exotic-all'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'blood-transfusions', 'oxygen-therapy'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 10. Westchester Veterinary Center (Limited Hours)
(
  'Westchester Veterinary Center',
  'westchester-vet-white-plains',
  '146 Clearbrook Rd',
  'Westchester',
  'NY',
  '10523',
  '(914) 949-1150',
  NULL,
  false,
  'emergency-only',
  41.0365,
  -73.7558,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'ultrasound-imaging'],
  true,
  false,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance'],
  false,
  true,
  'moderate',
  'free-lot',
  false,
  'unverified'
),

-- 11. Central Animal Hospital - Scarsdale (After-hours)
(
  'Central Animal Hospital',
  'central-animal-scarsdale',
  '5 Garth Rd',
  'Westchester',
  'NY',
  '10583',
  '(914) 723-1250',
  'https://www.centralanimalhospitalny.com',
  false,
  'extended-hours',
  40.9891,
  -73.8084,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'ultrasound-imaging'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'moderate',
  'street-only',
  false,
  'unverified'
),

-- 12. Yonkers Animal Hospital
(
  'Yonkers Animal Hospital',
  'yonkers-animal-hospital',
  '1930 Central Park Ave',
  'Westchester',
  'NY',
  '10710',
  '(914) 793-7400',
  NULL,
  false,
  'emergency-only',
  40.9551,
  -73.8637,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['ultrasound-imaging'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card'],
  false,
  false,
  'moderate',
  'free-lot',
  false,
  'unverified'
),

-- 13. Animal Medical Center - NYC (24/7, Luxury)
(
  'Animal Medical Center',
  'amc-nyc',
  '510 E 62nd St',
  'Westchester',
  'NY',
  '10065',
  '(212) 838-8100',
  'https://www.amcny.org',
  true,
  'true-24-7',
  40.7614,
  -73.9598,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'exotic-all'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'blood-transfusions', 'cardiology', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay', 'payment-plans'],
  true,
  true,
  'luxury',
  'valet',
  true,
  'verified'
),

-- 14. Oradell Animal Hospital - NJ (24/7, Premium)
(
  'Oradell Animal Hospital',
  'oradell-animal-hospital',
  '580 Winters Ave',
  'Westchester',
  'NJ',
  '07649',
  '(201) 262-0010',
  'https://www.oradell.com',
  true,
  'true-24-7',
  40.9539,
  -74.0375,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'small-mammals'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'cardiology', 'neurology', 'oncology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 15. BluePearl Pet Hospital Paramus (24/7, Premium)
(
  'BluePearl Pet Hospital Paramus',
  'bluepearl-paramus',
  '1 Route 4 West',
  'Westchester',
  'NJ',
  '07652',
  '(201) 603-0300',
  'https://bluepearlvet.com/hospital/paramus-nj',
  true,
  'true-24-7',
  40.9214,
  -74.0688,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'cardiology', 'oncology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 16. NorthStar VETS - NJ (24/7, Luxury)
(
  'NorthStar VETS',
  'northstar-vets-nj',
  '315 Robbinsville Allentown Rd',
  'Westchester',
  'NJ',
  '08691',
  '(609) 259-8300',
  'https://www.northstarvets.com',
  true,
  'true-24-7',
  40.2167,
  -74.5939,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'exotic-all'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'blood-transfusions', 'cardiology', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay', 'payment-plans'],
  true,
  true,
  'luxury',
  'free-lot',
  true,
  'verified'
),

-- =================================================================
-- ROCHESTER, NY (12 clinics)
-- =================================================================

-- 1. Rochester Emergency Veterinary Services (24/7)
(
  'Rochester Emergency Veterinary Services',
  'rochester-emergency-vet',
  '445 West Commercial St',
  'Rochester',
  'NY',
  '14445',
  '(585) 775-0020',
  'https://rocemergencyvet.com',
  true,
  'true-24-7',
  43.1018,
  -77.4987,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'oxygen-therapy'],
  true,
  true,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'moderate',
  'free-lot',
  true,
  'verified'
),

-- 2. ARK Veterinary Hospital (Extended Hours)
(
  'ARK Veterinary Hospital & Urgent Care',
  'ark-vet-henrietta',
  '35 Finn Rd',
  'Rochester',
  'NY',
  '14467',
  '(585) 487-8700',
  'https://www.arkvh.com',
  false,
  'extended-hours',
  43.0531,
  -77.6511,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'small-mammals'],
  true,
  ARRAY['emergency-surgery', 'ultrasound-imaging', 'oxygen-therapy'],
  true,
  false,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'moderate',
  'free-lot',
  true,
  'unverified'
),

-- 3. Animal Intermediate Care (Urgent Care)
(
  'Animal Intermediate Care',
  'animal-intermediate-webster',
  '896 Ridge Rd',
  'Rochester',
  'NY',
  '14580',
  '(585) 684-7901',
  'https://www.aicrochester.com',
  false,
  'urgent-care',
  43.2121,
  -77.4298,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['ultrasound-imaging', 'oxygen-therapy'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance'],
  false,
  true,
  'moderate',
  'free-lot',
  false,
  'unverified'
),

-- 4. Animal Hospital of Pittsford (Urgent Care)
(
  'Animal Hospital of Pittsford',
  'animal-hospital-pittsford',
  '2816 Monroe Ave',
  'Rochester',
  'NY',
  '14618',
  '(585) 271-7700',
  'https://www.pittsfordvet.com',
  false,
  'urgent-care',
  43.1008,
  -77.5274,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['ultrasound-imaging'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'moderate',
  'free-lot',
  false,
  'unverified'
),

-- 5. Daya Urgent Veterinary Services
(
  'Daya Urgent Veterinary Services',
  'daya-urgent-vet',
  '2800 Spencerport Rd',
  'Rochester',
  'NY',
  '14559',
  '(585) 488-1116',
  NULL,
  false,
  'urgent-care',
  43.1537,
  -77.7803,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['ultrasound-imaging'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card'],
  false,
  false,
  'budget',
  'free-lot',
  false,
  'unverified'
),

-- 6. Erie Canal Animal Hospital
(
  'Erie Canal Animal Hospital',
  'erie-canal-animal',
  '370 S Union St',
  'Rochester',
  'NY',
  '14559',
  '(585) 349-7387',
  NULL,
  false,
  'urgent-care',
  43.1856,
  -77.8063,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['ultrasound-imaging'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card'],
  false,
  false,
  'budget',
  'street-only',
  false,
  'unverified'
),

-- 7. BluePearl Pet Hospital Buffalo (24/7)
(
  'BluePearl Pet Hospital Buffalo',
  'bluepearl-buffalo',
  '4821 Genesee St',
  'Rochester',
  'NY',
  '14225',
  '(716) 839-4043',
  'https://bluepearlvet.com/hospital/buffalo-ny',
  true,
  'true-24-7',
  42.9458,
  -78.7543,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'cardiology', 'oncology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 8. Orchard Park Veterinary Medical Center (24/7)
(
  'Orchard Park Veterinary Medical Center',
  'orchard-park-vet',
  '3930 N Buffalo St',
  'Rochester',
  'NY',
  '14127',
  '(716) 662-6660',
  'https://www.opvmc.com',
  true,
  'true-24-7',
  42.7832,
  -78.7439,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'cardiology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 9. Green Acres Veterinary Center (24/7)
(
  'Green Acres Veterinary Center',
  'green-acres-vet',
  '2060 Niagara Falls Blvd',
  'Rochester',
  'NY',
  '14150',
  '(716) 694-0122',
  'https://greenacresveterinarycenter.com',
  true,
  'true-24-7',
  43.0186,
  -78.8792,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging'],
  true,
  true,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'moderate',
  'free-lot',
  true,
  'verified'
),

-- 10. Veterinary Medical Center of CNY (24/7)
(
  'Veterinary Medical Center of CNY',
  'vmc-cny-syracuse',
  '5841 Bridge St',
  'Rochester',
  'NY',
  '13057',
  '(315) 446-7933',
  'https://www.vmccny.com',
  true,
  'true-24-7',
  43.0659,
  -76.0719,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'cardiology', 'neurology'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit'],
  true,
  true,
  'premium',
  'free-lot',
  true,
  'verified'
),

-- 11. Cornell University Hospital for Animals (24/7, Luxury)
(
  'Cornell University Hospital for Animals',
  'cornell-vet-ithaca',
  '930 Campus Rd',
  'Rochester',
  'NY',
  '14853',
  '(607) 253-3060',
  'https://www.vet.cornell.edu/hospitals',
  true,
  'true-24-7',
  42.4478,
  -76.4654,
  ARRAY['dogs', 'cats', 'birds', 'reptiles', 'exotic-all'],
  true,
  ARRAY['emergency-surgery', 'icu-critical-care', 'overnight-monitoring', 'ultrasound-imaging', 'ct-scan', 'mri', 'blood-transfusions', 'cardiology', 'neurology', 'oncology', 'orthopedic'],
  true,
  true,
  true,
  ARRAY['cash', 'credit-card', 'pet-insurance', 'care-credit', 'scratchpay', 'payment-plans'],
  true,
  true,
  'luxury',
  'free-lot',
  true,
  'verified'
),

-- 12. Ridgemont Animal Hospital (Urgent Care)
(
  'Ridgemont Animal Hospital',
  'ridgemont-animal',
  '660 Middle Rd',
  'Rochester',
  'NY',
  '14624',
  '(585) 294-4766',
  'https://www.ridgemontanimalhospital.com',
  false,
  'urgent-care',
  43.1296,
  -77.7234,
  ARRAY['dogs', 'cats'],
  false,
  ARRAY['ultrasound-imaging'],
  false,
  false,
  false,
  ARRAY['cash', 'credit-card', 'pet-insurance'],
  false,
  true,
  'moderate',
  'free-lot',
  false,
  'unverified'
)

ON CONFLICT (slug) DO NOTHING;

-- =================================================================
-- UPDATE CITY CLINIC COUNTS
-- =================================================================

UPDATE cities 
SET clinic_count = (
    SELECT COUNT(*) 
    FROM clinics 
    WHERE clinics.city = cities.name AND clinics.state = cities.state
)
WHERE slug IN ('westchester', 'rochester');

-- =================================================================
-- VERIFICATION
-- =================================================================

-- Check how many clinics were inserted
SELECT city, state, COUNT(*) as clinic_count 
FROM clinics 
GROUP BY city, state 
ORDER BY city;

-- Check total count
SELECT COUNT(*) as total_clinics FROM clinics;

-- =================================================================
-- COMPLETE!
-- You now have 28 clinics in your database
-- Westchester: 16 clinics
-- Rochester: 12 clinics
-- =================================================================
